### ISSUE TITLE
HTTP 504 error after upload

### ISSUE THREAD

**Issue by MB-one** [Hasenlaeufer/LrMediaWiki#10]
After each upload batch (even if the upload actually went through), I will get the following error message:
"Warnung
Export nicht möglich:
HTTP-Status 504 erhalten"

My System:
- Lightroom Classic for Windows v9.4
- Windows 10.0.19041

**Comment by Hasenlaeufer** [comment]
The HTTP status 504 is a server error: Gateway timeout. This means that the server had temporary problems. The plugin cannot solve server problems, it can only pass the server error message on to the user.
