### ISSUE TITLE
Make categories modular (like keywords)

### ISSUE THREAD

**Issue by MB-one** [Hasenlaeufer/LrMediaWiki#11]
It would be a huge improvement, if the categories field works like keywords, instead of a single string.
That way one could easily add (or remove) categories to multiple files at once.

**Comment by Ezri** [comment]
While I can see issues with the Lighroom code to make that happen in librarymode, that should be possible via Zusatzmoduloptionen see the geoencode module as an example where you load a selection and then batch manipulate that selection. That would involve a few more clicks  compared to what happens at keywords, but would save quite a bit of time if you want to add one category to a larger number of files, where there are already conflicting categories.

**Comment by Hasenlaeufer** [comment]
This issue seems to be a duplicate of issue "Keyword-based categories #45" which has been implemented by v1.1.
Right?
If "yes", this issue can be closed.
If "no", we need to discuss the requirement further.

**Comment by MB-one** [comment]
Upon first glance, #25 seems to be a different approach to solve essentially the same problem. I'd have to test the new solution to be sure, but I guess, we can close this issue for now.
