### ISSUE TITLE
Feature: Update only

### ISSUE THREAD

**Issue by Ezri** [Hasenlaeufer/LrMediaWiki#12]
Ability to restrict an export to "update only" 
- When the filename does not exist -> Error
- (optional) One update comment for all files (saves the current having to enter the info for every file, which pauses the upload)

**Comment by Hasenlaeufer** [comment]
Please, can you illustrate the use case of this feature request a bit more?
Aren't both themes two different requirements?

**Comment by Ezri** [comment]
The use case of this feature would be if you want to explicitly update existing files (ie forgotten to apply lenscorrection). If the file under the current lightroom name does not exist the current situation would be to create a second file which should have only been an update. The requested feature would catch that error situation if selected and avoid the duplicate file.

the second part can be viewed independent as it can also be applied with normal uploads where some might be updates.
Either way when you have a larger number of files that are updated you have confirm each one with an update comment, so the upload cannot be left unattended. There a "apply comment to following update in this batch" checkbox, or at a minimum prefilling the comment box with the previous comment would be helpful.

**Comment by Hasenlaeufer** [comment]
Thanks!
I got it now.

**Comment by Hasenlaeufer** [comment]
This feature will be available in the upcoming 1.0 release. The implementation has been finished.

At export dialog there is a new selector: "Mode". Available are two values, "Standard" and "Update only".
"Standard" represents the well known behaviour.
"Update only" considers only files which are already available on the server.
If new files are part of the selection they will be ignored, an information message informs about this case.

The export in "Update only" mode starts with asking for an update comment for all selected files.
If the user input is filled, all updates will use this comment, there will not be any further question.
If the user input is empty or cancelled, for every file a comment is requested, as know from the "Standard" mode.

Does this fit the expectation?

**Comment by Hasenlaeufer** [comment]
Published by v1.0
