### ISSUE TITLE
Do not fill location template if "Remove Location Info" is checked

### ISSUE THREAD

**Issue by MB-one** [Hasenlaeufer/LrMediaWiki#13]
Despite "Remove Location Info" checked upon export, the tool currently fills the {{location}} template with GPS data. This defeats the purpose of the "Remove Location Info" functionality.

**Comment by Hasenlaeufer** [comment]
The upcoming next release 1.0 will deal with this issue, the implementation is completed.

There is a problem: The check box "Remove Location Info" is part of the section "Metadata" at export dialog. It's not inside one of both LrMediaWiki sections. In other words: The box is outside the scope of the plug-in. There is no method available by the SDK to get informed if the check box is set or not.
Therefore the plug-in introduces a workaround, a new check box:
English: Plug-in Manager… -> LrMediaWiki -> Enable {{Location}} template
German: Zusatzmodul-Manager… -> LrMediaWiki -> {{Location}}-Vorlage aktivieren
The {{location}} template will only be filled if this check box is set. The value of the check box is persistant. This means, Lightroom will remember the setting at next start.

**Comment by Hasenlaeufer** [comment]
Release 1.0.2: The check box has a default value "Off". It should be "On".

**Comment by Hasenlaeufer** [comment]
Published by v1.0
