### ISSUE TITLE
No way to work around 'was-deleted' upload error

### ISSUE THREAD

**Issue by mpeel** [Hasenlaeufer/LrMediaWiki#40]
I uploaded a file using LrMediaWiki, then realised I'd accidentally uploaded it with private exif data. So I deleted it on Commons, and tried to re-upload it. However, I get the message 'Upload failed: was-deleted (1)' - and there doesn't seem to be any way around this.

I'll upload the file again manually in this case, but it would be good to have an option to turn this off.

**Comment by Hasenlaeufer** [comment]
The error message is not generated by LrMediaWiki, it is caused by the server. So, my assumption is, if you try to "upload the file again manually" you will get the same error message. Right?
To deal with this case simply rename the file.

**Comment by mpeel** [comment]
I did get the same error when I manually uploaded the file - but I could then chose to upload anyway, and the file is now at the original filename without the private data. So there seems to be a way to override the error? (It's not a big issue, so if implementing a fix here would be difficult, it's better to simply close this issue.)

**Comment by Hasenlaeufer** [comment]
Yes, implementing a fix would be difficult ...

**Comment by mpeel** [comment]
Never mind then.
