### ISSUE TITLE
Doesn't work with two-factor authentication

### ISSUE THREAD

**Issue by magnusmanske** [Hasenlaeufer/LrMediaWiki#7]
TFA is a bit of a pain to implement, as I know from personal experience, but as someone who is just getting started with Lightroom, it would be really great to export quickly and easily to Commons

**Comment by Hasenlaeufer** [comment]
I added "help wanted". This means: What is a good starting point to implement TFA?
Any help is appreciated.

**Comment by Ezri** [comment]
I always thought that a bot password was the alternative anyway. https://en.wikipedia.org/wiki/Wikipedia:Using_AWB_with_2FA https://commons.wikimedia.org/wiki/Special:BotPasswords

**Comment by Hasenlaeufer** [comment]
Do we really need any implementation? @Ezri: Thanks for your comment.

**Comment by Hasenlaeufer** [comment]
As mentioned, a bot password is the solution.
