### ISSUE TITLE
Support for File captions

### ISSUE THREAD

**Issue by JeanFred** [Hasenlaeufer/LrMediaWiki#9]
[File captions](https://commons.wikimedia.org/wiki/Commons:File_captions) have been deployed to Wikimedia Commons last January. Support in LrMediaWiki would be much appreciated :)

For the similar issue in other community software:
* Commons Android App: https://github.com/commons-app/apps-android-commons/issues/2297 ; 
* Pattypan: https://github.com/yarl/pattypan/issues/92

Writing captions is done using an additional API call to  [`wbsetlabel`](https://www.mediawiki.org/wiki/Wikibase/API#wbsetlabel) − although, using the media ID (which is derived from the page_id, and thus needs to be retrieved post-upload via an API call).

**Comment by Hasenlaeufer** [comment]
Implemented by v1.2
